import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'components/accordion': 'src/components/ui/accordion.tsx',
    'components/alert': 'src/components/ui/alert.tsx',
    'components/autocomplete': 'src/components/ui/autocomplete.tsx',
    'components/avatar': 'src/components/ui/avatar.tsx',
    'components/badge': 'src/components/ui/badge.tsx',
    'components/banner': 'src/components/ui/banner.tsx',
    'components/bottom-nav': 'src/components/ui/bottom-nav.tsx',
    'components/breadcrumb': 'src/components/ui/breadcrumb.tsx',
    'components/button': 'src/components/ui/button.tsx',
    'components/calendar': 'src/components/ui/calendar.tsx',
    'components/card': 'src/components/ui/card.tsx',
    'components/carousel': 'src/components/ui/carousel.tsx',
    'components/checkbox': 'src/components/ui/checkbox.tsx',
    'components/chip': 'src/components/ui/chip.tsx',
    'components/color-picker': 'src/components/ui/color-picker.tsx',
    'components/combobox': 'src/components/ui/combobox.tsx',
    'components/context-menu': 'src/components/ui/context-menu.tsx',
    'components/data-block': 'src/components/ui/data-block.tsx',
    'components/date-picker': 'src/components/ui/date-picker.tsx',
    'components/dialog': 'src/components/ui/dialog.tsx',
    'components/divider': 'src/components/ui/divider.tsx',
    'components/dropdown-menu': 'src/components/ui/dropdown-menu.tsx',
    'components/empty-state': 'src/components/ui/empty-state.tsx',
    'components/file-upload': 'src/components/ui/file-upload.tsx',
    'components/footer-actions': 'src/components/ui/footer-actions.tsx',
    'components/header': 'src/components/ui/header.tsx',
    'components/input': 'src/components/ui/input.tsx',
    'components/lightbox': 'src/components/ui/lightbox.tsx',
    'components/link': 'src/components/ui/link.tsx',
    'components/list-item': 'src/components/ui/list-item.tsx',
    'components/media-hero': 'src/components/ui/media-hero.tsx',
    'components/navbar': 'src/components/ui/navbar.tsx',
    'components/number-input': 'src/components/ui/number-input.tsx',
    'components/number-stepper': 'src/components/ui/number-stepper.tsx',
    'components/pagination': 'src/components/ui/pagination.tsx',
    'components/phone-input': 'src/components/ui/phone-input.tsx',
    'components/pin-code': 'src/components/ui/pin-code.tsx',
    'components/popover': 'src/components/ui/popover.tsx',
    'components/progress': 'src/components/ui/progress.tsx',
    'components/property-card': 'src/components/ui/property-card.tsx',
    'components/radio': 'src/components/ui/radio.tsx',
    'components/rating': 'src/components/ui/rating.tsx',
    'components/search-input': 'src/components/ui/search-input.tsx',
    'components/select': 'src/components/ui/select.tsx',
    'components/sheet': 'src/components/ui/sheet.tsx',
    'components/side-nav': 'src/components/ui/side-nav.tsx',
    'components/skeleton': 'src/components/ui/skeleton.tsx',
    'components/slider': 'src/components/ui/slider.tsx',
    'components/stepper': 'src/components/ui/stepper.tsx',
    'components/switch': 'src/components/ui/switch.tsx',
    'components/table': 'src/components/ui/table.tsx',
    'components/tabs': 'src/components/ui/tabs.tsx',
    'components/tag': 'src/components/ui/tag.tsx',
    'components/tag-input': 'src/components/ui/tag-input.tsx',
    'components/text': 'src/components/ui/text.tsx',
    'components/timeline': 'src/components/ui/timeline.tsx',
    'components/toast': 'src/components/ui/toast.tsx',
    'components/toggle-group': 'src/components/ui/toggle-group.tsx',
    'components/tooltip': 'src/components/ui/tooltip.tsx',
    'components/uploader': 'src/components/ui/uploader.tsx',
  },
  format: ['cjs', 'esm'],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    '@radix-ui/react-dialog',
    '@radix-ui/react-select',
    '@radix-ui/react-slot',
    'lucide-react',
  ],
  treeshake: true,
})
